name: PlatformIO CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: '.python-version'

    - name: Install PlatformIO
      run: |
        pip install platformio

    - name: Run PlatformIO build
      run: |
        pio run

    - name: Upload bin-file as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-bin
        path: .pio/build/**/*.bin
        if-no-files-found: error

    - name: Create or Update PR Comment
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          :gift: bin が作成されました
          [こちらからダウンロードできます](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }})
